# Generated by Django 2.2 on 2019-09-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='icon',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
