# Generated by Django 2.1.8 on 2019-09-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tutorial_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialcategory',
            name='category_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
