# Generated by Django 2.2.4 on 2019-09-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tutorialcategory_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialcategory',
            name='category_img',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
