# Generated by Django 2.1.8 on 2019-09-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190907_0702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='cat_slug',
            new_name='slug',
        ),
    ]
