# Generated by Django 2.1.8 on 2019-09-07 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190907_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Category', verbose_name='Categories'),
        ),
    ]
