# Generated by Django 2.1.8 on 2019-09-07 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190907_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Category', to_field='category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
