# Generated by Django 2.1.8 on 2019-09-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190907_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='birthday',
            new_name='published',
        ),
    ]
